### ISSUE TITLE
Log warning message: Wrong Hostname in pic_settings

### ISSUE THREAD

**Issue by Gallore** [mrbeam/MrBeamPlugin#597]
Error message in the log file form mb_picture_preparation:
```
2019-10-09 14:33:56,505 - mb_picture_preparation - ERROR - Wrong Hostname in pic_settings. Should be <MrBeam-ANDY> but is <MrBeam-3D7F>
```

Looks like it's using a hostname from somewhere else....

```
pi@MrBeam-ANDY:~\> cat /etc/mrbeam
octopi=PROD 2018-01-12 19:15 1515784545
hostname=MrBeam-ANDY
device_series=2F
device_type=MrBeam2F
serial=00000000A7B1E5A4-2F
image_correction_markers=MrBeam2C-pink
pi@MrBeam-ANDY:~\> hostname
MrBeam-ANDY
```

**Comment by amrsoll** [comment]
Change `hostname_KEY: MrBeam-0E55` to `hostname_KEY: MrBeam-ANDY` in `.octoprint/cam/pic_settings.yaml`
This happened because you renamed the machine, however we don't want to get rid of that warning, since it could be because it is a sign that the machine could have been using the picture calibration set from an other machine.
